# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/collection/find_object.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/collection/find_object.proto',
  package='protodb.collection',
  syntax='proto3',
  serialized_pb=_b('\n$protodb/collection/find_object.proto\x12\x12protodb.collection\x1a google/protobuf/descriptor.proto\"E\n\x11\x46indObjectRequest\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x04\"\xdc\x01\n\x12\x46indObjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12H\n\x0c\x66\x61ilure_code\x18\x02 \x01(\x0e\x32\x32.protodb.collection.FindObjectResponse.FailureCode\x12\x0e\n\x06object\x18\x03 \x01(\x0c\"[\n\x0b\x46\x61ilureCode\x12\x0e\n\nNO_FAILURE\x10\x00\x12\x14\n\x10INVALID_DATABASE\x10\x01\x12\x16\n\x12INVALID_COLLECTION\x10\x02\x12\x0e\n\nINVALID_ID\x10\x03\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])



_FINDOBJECTRESPONSE_FAILURECODE = _descriptor.EnumDescriptor(
  name='FailureCode',
  full_name='protodb.collection.FindObjectResponse.FailureCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_FAILURE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DATABASE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_COLLECTION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_ID', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=295,
  serialized_end=386,
)
_sym_db.RegisterEnumDescriptor(_FINDOBJECTRESPONSE_FAILURECODE)


_FINDOBJECTREQUEST = _descriptor.Descriptor(
  name='FindObjectRequest',
  full_name='protodb.collection.FindObjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.collection.FindObjectRequest.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collection', full_name='protodb.collection.FindObjectRequest.collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='protodb.collection.FindObjectRequest.id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=163,
)


_FINDOBJECTRESPONSE = _descriptor.Descriptor(
  name='FindObjectResponse',
  full_name='protodb.collection.FindObjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='protodb.collection.FindObjectResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failure_code', full_name='protodb.collection.FindObjectResponse.failure_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='protodb.collection.FindObjectResponse.object', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FINDOBJECTRESPONSE_FAILURECODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=386,
)

_FINDOBJECTRESPONSE.fields_by_name['failure_code'].enum_type = _FINDOBJECTRESPONSE_FAILURECODE
_FINDOBJECTRESPONSE_FAILURECODE.containing_type = _FINDOBJECTRESPONSE
DESCRIPTOR.message_types_by_name['FindObjectRequest'] = _FINDOBJECTREQUEST
DESCRIPTOR.message_types_by_name['FindObjectResponse'] = _FINDOBJECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindObjectRequest = _reflection.GeneratedProtocolMessageType('FindObjectRequest', (_message.Message,), dict(
  DESCRIPTOR = _FINDOBJECTREQUEST,
  __module__ = 'protodb.collection.find_object_pb2'
  # @@protoc_insertion_point(class_scope:protodb.collection.FindObjectRequest)
  ))
_sym_db.RegisterMessage(FindObjectRequest)

FindObjectResponse = _reflection.GeneratedProtocolMessageType('FindObjectResponse', (_message.Message,), dict(
  DESCRIPTOR = _FINDOBJECTRESPONSE,
  __module__ = 'protodb.collection.find_object_pb2'
  # @@protoc_insertion_point(class_scope:protodb.collection.FindObjectResponse)
  ))
_sym_db.RegisterMessage(FindObjectResponse)


# @@protoc_insertion_point(module_scope)
