# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/collection/list.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/collection/list.proto',
  package='protodb.collection',
  syntax='proto3',
  serialized_pb=_b('\n\x1dprotodb/collection/list.proto\x12\x12protodb.collection\"*\n\x16ListCollectionsRequest\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\"\xec\x01\n\x17ListCollectionsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12M\n\x0c\x66\x61ilure_code\x18\x02 \x01(\x0e\x32\x37.protodb.collection.ListCollectionsResponse.FailureCode\x12\x13\n\x0b\x63ollections\x18\x03 \x03(\t\"\\\n\x0b\x46\x61ilureCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x14\n\x10INVALID_DATABASE\x10\x01\x12\x15\n\x11\x43OLLECTION_EXISTS\x10\x02\x12\x12\n\x0eINVALID_SCHEMA\x10\x03\x62\x06proto3')
)



_LISTCOLLECTIONSRESPONSE_FAILURECODE = _descriptor.EnumDescriptor(
  name='FailureCode',
  full_name='protodb.collection.ListCollectionsResponse.FailureCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DATABASE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLLECTION_EXISTS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_SCHEMA', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=242,
  serialized_end=334,
)
_sym_db.RegisterEnumDescriptor(_LISTCOLLECTIONSRESPONSE_FAILURECODE)


_LISTCOLLECTIONSREQUEST = _descriptor.Descriptor(
  name='ListCollectionsRequest',
  full_name='protodb.collection.ListCollectionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.collection.ListCollectionsRequest.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=95,
)


_LISTCOLLECTIONSRESPONSE = _descriptor.Descriptor(
  name='ListCollectionsResponse',
  full_name='protodb.collection.ListCollectionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='protodb.collection.ListCollectionsResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failure_code', full_name='protodb.collection.ListCollectionsResponse.failure_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collections', full_name='protodb.collection.ListCollectionsResponse.collections', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LISTCOLLECTIONSRESPONSE_FAILURECODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=334,
)

_LISTCOLLECTIONSRESPONSE.fields_by_name['failure_code'].enum_type = _LISTCOLLECTIONSRESPONSE_FAILURECODE
_LISTCOLLECTIONSRESPONSE_FAILURECODE.containing_type = _LISTCOLLECTIONSRESPONSE
DESCRIPTOR.message_types_by_name['ListCollectionsRequest'] = _LISTCOLLECTIONSREQUEST
DESCRIPTOR.message_types_by_name['ListCollectionsResponse'] = _LISTCOLLECTIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListCollectionsRequest = _reflection.GeneratedProtocolMessageType('ListCollectionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTCOLLECTIONSREQUEST,
  __module__ = 'protodb.collection.list_pb2'
  # @@protoc_insertion_point(class_scope:protodb.collection.ListCollectionsRequest)
  ))
_sym_db.RegisterMessage(ListCollectionsRequest)

ListCollectionsResponse = _reflection.GeneratedProtocolMessageType('ListCollectionsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTCOLLECTIONSRESPONSE,
  __module__ = 'protodb.collection.list_pb2'
  # @@protoc_insertion_point(class_scope:protodb.collection.ListCollectionsResponse)
  ))
_sym_db.RegisterMessage(ListCollectionsResponse)


# @@protoc_insertion_point(module_scope)
