# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/extensions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/extensions.proto',
  package='protodb',
  syntax='proto3',
  serialized_pb=_b('\n\x18protodb/extensions.proto\x12\x07protodb\x1a google/protobuf/descriptor.proto\"%\n\x0eProtoDBOptions\x12\x13\n\x0bprimary_key\x18\x01 \x01(\x08:I\n\x07protodb\x12\x1d.google.protobuf.FieldOptions\x18\xb8\xb6\x05 \x01(\x0b\x32\x17.protodb.ProtoDBOptionsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


PROTODB_FIELD_NUMBER = 88888
protodb = _descriptor.FieldDescriptor(
  name='protodb', full_name='protodb.protodb', index=0,
  number=88888, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)


_PROTODBOPTIONS = _descriptor.Descriptor(
  name='ProtoDBOptions',
  full_name='protodb.ProtoDBOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='primary_key', full_name='protodb.ProtoDBOptions.primary_key', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['ProtoDBOptions'] = _PROTODBOPTIONS
DESCRIPTOR.extensions_by_name['protodb'] = protodb
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoDBOptions = _reflection.GeneratedProtocolMessageType('ProtoDBOptions', (_message.Message,), dict(
  DESCRIPTOR = _PROTODBOPTIONS,
  __module__ = 'protodb.extensions_pb2'
  # @@protoc_insertion_point(class_scope:protodb.ProtoDBOptions)
  ))
_sym_db.RegisterMessage(ProtoDBOptions)

protodb.message_type = _PROTODBOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(protodb)

# @@protoc_insertion_point(module_scope)
