# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/protodb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protodb import collection_create_pb2 as protodb_dot_collection__create__pb2
from protodb import database_create_pb2 as protodb_dot_database__create__pb2
from protodb import database_list_pb2 as protodb_dot_database__list__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/protodb.proto',
  package='protodb',
  syntax='proto3',
  serialized_pb=_b('\n\x15protodb/protodb.proto\x12\x07protodb\x1a\x1fprotodb/collection_create.proto\x1a\x1dprotodb/database_create.proto\x1a\x1bprotodb/database_list.proto2\x85\x02\n\x07ProtoDB\x12Q\n\x0e\x43reateDatabase\x12\x1e.protodb.CreateDatabaseRequest\x1a\x1f.protodb.CreateDatabaseResponse\x12N\n\rListDatabases\x12\x1d.protodb.ListDatabasesRequest\x1a\x1e.protodb.ListDatabasesResponse\x12W\n\x10\x43reateCollection\x12 .protodb.CreateCollectionRequest\x1a!.protodb.CreateCollectionResponseb\x06proto3')
  ,
  dependencies=[protodb_dot_collection__create__pb2.DESCRIPTOR,protodb_dot_database__create__pb2.DESCRIPTOR,protodb_dot_database__list__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PROTODB = _descriptor.ServiceDescriptor(
  name='ProtoDB',
  full_name='protodb.ProtoDB',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=128,
  serialized_end=389,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateDatabase',
    full_name='protodb.ProtoDB.CreateDatabase',
    index=0,
    containing_service=None,
    input_type=protodb_dot_database__create__pb2._CREATEDATABASEREQUEST,
    output_type=protodb_dot_database__create__pb2._CREATEDATABASERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListDatabases',
    full_name='protodb.ProtoDB.ListDatabases',
    index=1,
    containing_service=None,
    input_type=protodb_dot_database__list__pb2._LISTDATABASESREQUEST,
    output_type=protodb_dot_database__list__pb2._LISTDATABASESRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateCollection',
    full_name='protodb.ProtoDB.CreateCollection',
    index=2,
    containing_service=None,
    input_type=protodb_dot_collection__create__pb2._CREATECOLLECTIONREQUEST,
    output_type=protodb_dot_collection__create__pb2._CREATECOLLECTIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROTODB)

DESCRIPTOR.services_by_name['ProtoDB'] = _PROTODB

# @@protoc_insertion_point(module_scope)
