# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/protodb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protodb.collection import create_pb2 as protodb_dot_collection_dot_create__pb2
from protodb.collection import insert_object_pb2 as protodb_dot_collection_dot_insert__object__pb2
from protodb.collection import list_pb2 as protodb_dot_collection_dot_list__pb2
from protodb.database import create_pb2 as protodb_dot_database_dot_create__pb2
from protodb.database import list_pb2 as protodb_dot_database_dot_list__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/protodb.proto',
  package='protodb',
  syntax='proto3',
  serialized_pb=_b('\n\x15protodb/protodb.proto\x12\x07protodb\x1a\x1fprotodb/collection/create.proto\x1a&protodb/collection/insert_object.proto\x1a\x1dprotodb/collection/list.proto\x1a\x1dprotodb/database/create.proto\x1a\x1bprotodb/database/list.proto2\x8e\x04\n\x07ProtoDB\x12\x63\n\x0e\x43reateDatabase\x12\'.protodb.database.CreateDatabaseRequest\x1a(.protodb.database.CreateDatabaseResponse\x12`\n\rListDatabases\x12&.protodb.database.ListDatabasesRequest\x1a\'.protodb.database.ListDatabasesResponse\x12m\n\x10\x43reateCollection\x12+.protodb.collection.CreateCollectionRequest\x1a,.protodb.collection.CreateCollectionResponse\x12j\n\x0fListCollections\x12*.protodb.collection.ListCollectionsRequest\x1a+.protodb.collection.ListCollectionsResponse\x12\x61\n\x0cInsertObject\x12\'.protodb.collection.InsertObjectRequest\x1a(.protodb.collection.InsertObjectResponseb\x06proto3')
  ,
  dependencies=[protodb_dot_collection_dot_create__pb2.DESCRIPTOR,protodb_dot_collection_dot_insert__object__pb2.DESCRIPTOR,protodb_dot_collection_dot_list__pb2.DESCRIPTOR,protodb_dot_database_dot_create__pb2.DESCRIPTOR,protodb_dot_database_dot_list__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PROTODB = _descriptor.ServiceDescriptor(
  name='ProtoDB',
  full_name='protodb.ProtoDB',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=199,
  serialized_end=725,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateDatabase',
    full_name='protodb.ProtoDB.CreateDatabase',
    index=0,
    containing_service=None,
    input_type=protodb_dot_database_dot_create__pb2._CREATEDATABASEREQUEST,
    output_type=protodb_dot_database_dot_create__pb2._CREATEDATABASERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListDatabases',
    full_name='protodb.ProtoDB.ListDatabases',
    index=1,
    containing_service=None,
    input_type=protodb_dot_database_dot_list__pb2._LISTDATABASESREQUEST,
    output_type=protodb_dot_database_dot_list__pb2._LISTDATABASESRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateCollection',
    full_name='protodb.ProtoDB.CreateCollection',
    index=2,
    containing_service=None,
    input_type=protodb_dot_collection_dot_create__pb2._CREATECOLLECTIONREQUEST,
    output_type=protodb_dot_collection_dot_create__pb2._CREATECOLLECTIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListCollections',
    full_name='protodb.ProtoDB.ListCollections',
    index=3,
    containing_service=None,
    input_type=protodb_dot_collection_dot_list__pb2._LISTCOLLECTIONSREQUEST,
    output_type=protodb_dot_collection_dot_list__pb2._LISTCOLLECTIONSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InsertObject',
    full_name='protodb.ProtoDB.InsertObject',
    index=4,
    containing_service=None,
    input_type=protodb_dot_collection_dot_insert__object__pb2._INSERTOBJECTREQUEST,
    output_type=protodb_dot_collection_dot_insert__object__pb2._INSERTOBJECTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROTODB)

DESCRIPTOR.services_by_name['ProtoDB'] = _PROTODB

# @@protoc_insertion_point(module_scope)
