# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/object/insert.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/object/insert.proto',
  package='protodb.object',
  syntax='proto3',
  serialized_pb=_b('\n\x1bprotodb/object/insert.proto\x12\x0eprotodb.object\"K\n\x13InsertObjectRequest\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\x0c\"\xd0\x03\n\x14InsertObjectResponse\x12\x42\n\nerror_code\x18\x01 \x01(\x0e\x32..protodb.object.InsertObjectResponse.ErrorCode\x12\x46\n\x0cobject_error\x18\x02 \x01(\x0b\x32\x30.protodb.object.InsertObjectResponse.ObjectError\x1a\xa8\x01\n\x0bObjectError\x12N\n\x04\x63ode\x18\x01 \x01(\x0e\x32@.protodb.object.InsertObjectResponse.ObjectError.ObjectErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x0fObjectErrorCode\x12\x13\n\x0fNO_OBJECT_ERROR\x10\x00\x12\x10\n\x0c\x44\x45\x43ODE_ERROR\x10\x01\"\x80\x01\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x14\n\x10INVALID_DATABASE\x10\x02\x12\x16\n\x12INVALID_COLLECTION\x10\x03\x12\x11\n\rOBJECT_EXISTS\x10\x04\x12\x10\n\x0cOBJECT_ERROR\x10\x05\x62\x06proto3')
)



_INSERTOBJECTRESPONSE_OBJECTERROR_OBJECTERRORCODE = _descriptor.EnumDescriptor(
  name='ObjectErrorCode',
  full_name='protodb.object.InsertObjectResponse.ObjectError.ObjectErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_OBJECT_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECODE_ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=402,
  serialized_end=458,
)
_sym_db.RegisterEnumDescriptor(_INSERTOBJECTRESPONSE_OBJECTERROR_OBJECTERRORCODE)

_INSERTOBJECTRESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='protodb.object.InsertObjectResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DATABASE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_COLLECTION', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBJECT_EXISTS', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBJECT_ERROR', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=461,
  serialized_end=589,
)
_sym_db.RegisterEnumDescriptor(_INSERTOBJECTRESPONSE_ERRORCODE)


_INSERTOBJECTREQUEST = _descriptor.Descriptor(
  name='InsertObjectRequest',
  full_name='protodb.object.InsertObjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.object.InsertObjectRequest.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collection', full_name='protodb.object.InsertObjectRequest.collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='protodb.object.InsertObjectRequest.object', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=122,
)


_INSERTOBJECTRESPONSE_OBJECTERROR = _descriptor.Descriptor(
  name='ObjectError',
  full_name='protodb.object.InsertObjectResponse.ObjectError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protodb.object.InsertObjectResponse.ObjectError.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='protodb.object.InsertObjectResponse.ObjectError.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INSERTOBJECTRESPONSE_OBJECTERROR_OBJECTERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=458,
)

_INSERTOBJECTRESPONSE = _descriptor.Descriptor(
  name='InsertObjectResponse',
  full_name='protodb.object.InsertObjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='protodb.object.InsertObjectResponse.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_error', full_name='protodb.object.InsertObjectResponse.object_error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INSERTOBJECTRESPONSE_OBJECTERROR, ],
  enum_types=[
    _INSERTOBJECTRESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=589,
)

_INSERTOBJECTRESPONSE_OBJECTERROR.fields_by_name['code'].enum_type = _INSERTOBJECTRESPONSE_OBJECTERROR_OBJECTERRORCODE
_INSERTOBJECTRESPONSE_OBJECTERROR.containing_type = _INSERTOBJECTRESPONSE
_INSERTOBJECTRESPONSE_OBJECTERROR_OBJECTERRORCODE.containing_type = _INSERTOBJECTRESPONSE_OBJECTERROR
_INSERTOBJECTRESPONSE.fields_by_name['error_code'].enum_type = _INSERTOBJECTRESPONSE_ERRORCODE
_INSERTOBJECTRESPONSE.fields_by_name['object_error'].message_type = _INSERTOBJECTRESPONSE_OBJECTERROR
_INSERTOBJECTRESPONSE_ERRORCODE.containing_type = _INSERTOBJECTRESPONSE
DESCRIPTOR.message_types_by_name['InsertObjectRequest'] = _INSERTOBJECTREQUEST
DESCRIPTOR.message_types_by_name['InsertObjectResponse'] = _INSERTOBJECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertObjectRequest = _reflection.GeneratedProtocolMessageType('InsertObjectRequest', (_message.Message,), dict(
  DESCRIPTOR = _INSERTOBJECTREQUEST,
  __module__ = 'protodb.object.insert_pb2'
  # @@protoc_insertion_point(class_scope:protodb.object.InsertObjectRequest)
  ))
_sym_db.RegisterMessage(InsertObjectRequest)

InsertObjectResponse = _reflection.GeneratedProtocolMessageType('InsertObjectResponse', (_message.Message,), dict(

  ObjectError = _reflection.GeneratedProtocolMessageType('ObjectError', (_message.Message,), dict(
    DESCRIPTOR = _INSERTOBJECTRESPONSE_OBJECTERROR,
    __module__ = 'protodb.object.insert_pb2'
    # @@protoc_insertion_point(class_scope:protodb.object.InsertObjectResponse.ObjectError)
    ))
  ,
  DESCRIPTOR = _INSERTOBJECTRESPONSE,
  __module__ = 'protodb.object.insert_pb2'
  # @@protoc_insertion_point(class_scope:protodb.object.InsertObjectResponse)
  ))
_sym_db.RegisterMessage(InsertObjectResponse)
_sym_db.RegisterMessage(InsertObjectResponse.ObjectError)


# @@protoc_insertion_point(module_scope)
