# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/collection/get_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/collection/get_info.proto',
  package='protodb.collection',
  syntax='proto3',
  serialized_pb=_b('\n!protodb/collection/get_info.proto\x12\x12protodb.collection\x1a google/protobuf/descriptor.proto\"@\n\x18GetCollectionInfoRequest\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\"\xf7\x01\n\x19GetCollectionInfoResponse\x12K\n\nerror_code\x18\x01 \x01(\x0e\x32\x37.protodb.collection.GetCollectionInfoResponse.ErrorCode\x12\x30\n\x06schema\x18\x02 \x01(\x0b\x32 .google.protobuf.DescriptorProto\"[\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x14\n\x10INVALID_DATABASE\x10\x02\x12\x16\n\x12INVALID_COLLECTION\x10\x03\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])



_GETCOLLECTIONINFORESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='protodb.collection.GetCollectionInfoResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DATABASE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_COLLECTION', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=314,
  serialized_end=405,
)
_sym_db.RegisterEnumDescriptor(_GETCOLLECTIONINFORESPONSE_ERRORCODE)


_GETCOLLECTIONINFOREQUEST = _descriptor.Descriptor(
  name='GetCollectionInfoRequest',
  full_name='protodb.collection.GetCollectionInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.collection.GetCollectionInfoRequest.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collection', full_name='protodb.collection.GetCollectionInfoRequest.collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=155,
)


_GETCOLLECTIONINFORESPONSE = _descriptor.Descriptor(
  name='GetCollectionInfoResponse',
  full_name='protodb.collection.GetCollectionInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='protodb.collection.GetCollectionInfoResponse.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schema', full_name='protodb.collection.GetCollectionInfoResponse.schema', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETCOLLECTIONINFORESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=405,
)

_GETCOLLECTIONINFORESPONSE.fields_by_name['error_code'].enum_type = _GETCOLLECTIONINFORESPONSE_ERRORCODE
_GETCOLLECTIONINFORESPONSE.fields_by_name['schema'].message_type = google_dot_protobuf_dot_descriptor__pb2._DESCRIPTORPROTO
_GETCOLLECTIONINFORESPONSE_ERRORCODE.containing_type = _GETCOLLECTIONINFORESPONSE
DESCRIPTOR.message_types_by_name['GetCollectionInfoRequest'] = _GETCOLLECTIONINFOREQUEST
DESCRIPTOR.message_types_by_name['GetCollectionInfoResponse'] = _GETCOLLECTIONINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCollectionInfoRequest = _reflection.GeneratedProtocolMessageType('GetCollectionInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCOLLECTIONINFOREQUEST,
  __module__ = 'protodb.collection.get_info_pb2'
  # @@protoc_insertion_point(class_scope:protodb.collection.GetCollectionInfoRequest)
  ))
_sym_db.RegisterMessage(GetCollectionInfoRequest)

GetCollectionInfoResponse = _reflection.GeneratedProtocolMessageType('GetCollectionInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCOLLECTIONINFORESPONSE,
  __module__ = 'protodb.collection.get_info_pb2'
  # @@protoc_insertion_point(class_scope:protodb.collection.GetCollectionInfoResponse)
  ))
_sym_db.RegisterMessage(GetCollectionInfoResponse)


# @@protoc_insertion_point(module_scope)
