# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/wasm/get_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/wasm/get_info.proto',
  package='protodb.wasm',
  syntax='proto3',
  serialized_pb=_b('\n\x1bprotodb/wasm/get_info.proto\x12\x0cprotodb.wasm\x1a google/protobuf/descriptor.proto\"6\n\x14GetModuleInfoRequest\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xec\x01\n\x15GetModuleInfoResponse\x12\x41\n\nerror_code\x18\x01 \x01(\x0e\x32-.protodb.wasm.GetModuleInfoResponse.ErrorCode\x12\x37\n\rresult_schema\x18\x02 \x01(\x0b\x32 .google.protobuf.DescriptorProto\"W\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x14\n\x10INVALID_DATABASE\x10\x02\x12\x12\n\x0eINVALID_MODULE\x10\x03\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])



_GETMODULEINFORESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='protodb.wasm.GetModuleInfoResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DATABASE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_MODULE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=285,
  serialized_end=372,
)
_sym_db.RegisterEnumDescriptor(_GETMODULEINFORESPONSE_ERRORCODE)


_GETMODULEINFOREQUEST = _descriptor.Descriptor(
  name='GetModuleInfoRequest',
  full_name='protodb.wasm.GetModuleInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.wasm.GetModuleInfoRequest.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protodb.wasm.GetModuleInfoRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=133,
)


_GETMODULEINFORESPONSE = _descriptor.Descriptor(
  name='GetModuleInfoResponse',
  full_name='protodb.wasm.GetModuleInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='protodb.wasm.GetModuleInfoResponse.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_schema', full_name='protodb.wasm.GetModuleInfoResponse.result_schema', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETMODULEINFORESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=372,
)

_GETMODULEINFORESPONSE.fields_by_name['error_code'].enum_type = _GETMODULEINFORESPONSE_ERRORCODE
_GETMODULEINFORESPONSE.fields_by_name['result_schema'].message_type = google_dot_protobuf_dot_descriptor__pb2._DESCRIPTORPROTO
_GETMODULEINFORESPONSE_ERRORCODE.containing_type = _GETMODULEINFORESPONSE
DESCRIPTOR.message_types_by_name['GetModuleInfoRequest'] = _GETMODULEINFOREQUEST
DESCRIPTOR.message_types_by_name['GetModuleInfoResponse'] = _GETMODULEINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetModuleInfoRequest = _reflection.GeneratedProtocolMessageType('GetModuleInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETMODULEINFOREQUEST,
  __module__ = 'protodb.wasm.get_info_pb2'
  # @@protoc_insertion_point(class_scope:protodb.wasm.GetModuleInfoRequest)
  ))
_sym_db.RegisterMessage(GetModuleInfoRequest)

GetModuleInfoResponse = _reflection.GeneratedProtocolMessageType('GetModuleInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETMODULEINFORESPONSE,
  __module__ = 'protodb.wasm.get_info_pb2'
  # @@protoc_insertion_point(class_scope:protodb.wasm.GetModuleInfoResponse)
  ))
_sym_db.RegisterMessage(GetModuleInfoResponse)


# @@protoc_insertion_point(module_scope)
