# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/wasm/register.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/wasm/register.proto',
  package='protodb.wasm',
  syntax='proto3',
  serialized_pb=_b('\n\x1bprotodb/wasm/register.proto\x12\x0cprotodb.wasm\x1a google/protobuf/descriptor.proto\"\x90\x04\n\x15RegisterModuleRequest\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x44\n\x08metadata\x18\x03 \x01(\x0b\x32\x32.protodb.wasm.RegisterModuleRequest.ModuleMetadata\x12\x0c\n\x04wasm\x18\x04 \x01(\x0c\x12\x37\n\rresult_schema\x18\x05 \x01(\x0b\x32 .google.protobuf.DescriptorProto\x1a\xc9\x02\n\x0eModuleMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x65\n\x15\x62indgen_import_hashes\x18\x02 \x01(\x0b\x32\x46.protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes\x1a\xc1\x01\n\x13\x42indgenImportHashes\x12\x0b\n\x03log\x18\x01 \x01(\t\x12\x13\n\x0b\x66ind_object\x18\x02 \x01(\t\x12\x19\n\x11\x66ind_objects_iter\x18\x03 \x01(\t\x12\x1e\n\x16\x66ind_objects_iter_next\x18\x04 \x01(\t\x12\x12\n\nindex_iter\x18\x05 \x01(\t\x12\x1d\n\x15index_iter_next_value\x18\x06 \x01(\t\x12\x1a\n\x12index_iter_next_id\x18\x07 \x01(\t\"\xb4\x01\n\x16RegisterModuleResponse\x12\x42\n\nerror_code\x18\x01 \x01(\x0e\x32..protodb.wasm.RegisterModuleResponse.ErrorCode\"V\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x14\n\x10INVALID_DATABASE\x10\x02\x12\x11\n\rMODULE_EXISTS\x10\x03\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])



_REGISTERMODULERESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='protodb.wasm.RegisterModuleResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DATABASE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODULE_EXISTS', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=705,
  serialized_end=791,
)
_sym_db.RegisterEnumDescriptor(_REGISTERMODULERESPONSE_ERRORCODE)


_REGISTERMODULEREQUEST_MODULEMETADATA_BINDGENIMPORTHASHES = _descriptor.Descriptor(
  name='BindgenImportHashes',
  full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes.log', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='find_object', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes.find_object', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='find_objects_iter', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes.find_objects_iter', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='find_objects_iter_next', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes.find_objects_iter_next', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_iter', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes.index_iter', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_iter_next_value', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes.index_iter_next_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index_iter_next_id', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes.index_iter_next_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=608,
)

_REGISTERMODULEREQUEST_MODULEMETADATA = _descriptor.Descriptor(
  name='ModuleMetadata',
  full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bindgen_import_hashes', full_name='protodb.wasm.RegisterModuleRequest.ModuleMetadata.bindgen_import_hashes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REGISTERMODULEREQUEST_MODULEMETADATA_BINDGENIMPORTHASHES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=608,
)

_REGISTERMODULEREQUEST = _descriptor.Descriptor(
  name='RegisterModuleRequest',
  full_name='protodb.wasm.RegisterModuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.wasm.RegisterModuleRequest.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protodb.wasm.RegisterModuleRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='protodb.wasm.RegisterModuleRequest.metadata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wasm', full_name='protodb.wasm.RegisterModuleRequest.wasm', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_schema', full_name='protodb.wasm.RegisterModuleRequest.result_schema', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REGISTERMODULEREQUEST_MODULEMETADATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=608,
)


_REGISTERMODULERESPONSE = _descriptor.Descriptor(
  name='RegisterModuleResponse',
  full_name='protodb.wasm.RegisterModuleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='protodb.wasm.RegisterModuleResponse.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REGISTERMODULERESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=791,
)

_REGISTERMODULEREQUEST_MODULEMETADATA_BINDGENIMPORTHASHES.containing_type = _REGISTERMODULEREQUEST_MODULEMETADATA
_REGISTERMODULEREQUEST_MODULEMETADATA.fields_by_name['bindgen_import_hashes'].message_type = _REGISTERMODULEREQUEST_MODULEMETADATA_BINDGENIMPORTHASHES
_REGISTERMODULEREQUEST_MODULEMETADATA.containing_type = _REGISTERMODULEREQUEST
_REGISTERMODULEREQUEST.fields_by_name['metadata'].message_type = _REGISTERMODULEREQUEST_MODULEMETADATA
_REGISTERMODULEREQUEST.fields_by_name['result_schema'].message_type = google_dot_protobuf_dot_descriptor__pb2._DESCRIPTORPROTO
_REGISTERMODULERESPONSE.fields_by_name['error_code'].enum_type = _REGISTERMODULERESPONSE_ERRORCODE
_REGISTERMODULERESPONSE_ERRORCODE.containing_type = _REGISTERMODULERESPONSE
DESCRIPTOR.message_types_by_name['RegisterModuleRequest'] = _REGISTERMODULEREQUEST
DESCRIPTOR.message_types_by_name['RegisterModuleResponse'] = _REGISTERMODULERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterModuleRequest = _reflection.GeneratedProtocolMessageType('RegisterModuleRequest', (_message.Message,), dict(

  ModuleMetadata = _reflection.GeneratedProtocolMessageType('ModuleMetadata', (_message.Message,), dict(

    BindgenImportHashes = _reflection.GeneratedProtocolMessageType('BindgenImportHashes', (_message.Message,), dict(
      DESCRIPTOR = _REGISTERMODULEREQUEST_MODULEMETADATA_BINDGENIMPORTHASHES,
      __module__ = 'protodb.wasm.register_pb2'
      # @@protoc_insertion_point(class_scope:protodb.wasm.RegisterModuleRequest.ModuleMetadata.BindgenImportHashes)
      ))
    ,
    DESCRIPTOR = _REGISTERMODULEREQUEST_MODULEMETADATA,
    __module__ = 'protodb.wasm.register_pb2'
    # @@protoc_insertion_point(class_scope:protodb.wasm.RegisterModuleRequest.ModuleMetadata)
    ))
  ,
  DESCRIPTOR = _REGISTERMODULEREQUEST,
  __module__ = 'protodb.wasm.register_pb2'
  # @@protoc_insertion_point(class_scope:protodb.wasm.RegisterModuleRequest)
  ))
_sym_db.RegisterMessage(RegisterModuleRequest)
_sym_db.RegisterMessage(RegisterModuleRequest.ModuleMetadata)
_sym_db.RegisterMessage(RegisterModuleRequest.ModuleMetadata.BindgenImportHashes)

RegisterModuleResponse = _reflection.GeneratedProtocolMessageType('RegisterModuleResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERMODULERESPONSE,
  __module__ = 'protodb.wasm.register_pb2'
  # @@protoc_insertion_point(class_scope:protodb.wasm.RegisterModuleResponse)
  ))
_sym_db.RegisterMessage(RegisterModuleResponse)


# @@protoc_insertion_point(module_scope)
