# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/collection_create.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/collection_create.proto',
  package='protodb.server',
  syntax='proto3',
  serialized_pb=_b('\n\x1eserver/collection_create.proto\x12\x0eprotodb.server\x1a google/protobuf/descriptor.proto\"d\n\x10\x43reateCollection\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x30\n\x06schema\x18\x03 \x01(\x0b\x32 .google.protobuf.DescriptorProto\"\xd9\x01\n\x18\x43reateCollectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12J\n\x0c\x66\x61ilure_code\x18\x02 \x01(\x0e\x32\x34.protodb.server.CreateCollectionResponse.FailureCode\"`\n\x0b\x46\x61ilureCode\x12\x0e\n\nINVALID_DB\x10\x00\x12\x16\n\x12INVALID_COLLECTION\x10\x01\x12\x15\n\x11\x43OLLECTION_EXISTS\x10\x02\x12\x12\n\x0eINVALID_SCHEMA\x10\x03\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CREATECOLLECTIONRESPONSE_FAILURECODE = _descriptor.EnumDescriptor(
  name='FailureCode',
  full_name='protodb.server.CreateCollectionResponse.FailureCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_DB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_COLLECTION', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLLECTION_EXISTS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_SCHEMA', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=308,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_CREATECOLLECTIONRESPONSE_FAILURECODE)


_CREATECOLLECTION = _descriptor.Descriptor(
  name='CreateCollection',
  full_name='protodb.server.CreateCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.server.CreateCollection.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='protodb.server.CreateCollection.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='schema', full_name='protodb.server.CreateCollection.schema', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=184,
)


_CREATECOLLECTIONRESPONSE = _descriptor.Descriptor(
  name='CreateCollectionResponse',
  full_name='protodb.server.CreateCollectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='protodb.server.CreateCollectionResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_code', full_name='protodb.server.CreateCollectionResponse.failure_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CREATECOLLECTIONRESPONSE_FAILURECODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=404,
)

_CREATECOLLECTION.fields_by_name['schema'].message_type = google_dot_protobuf_dot_descriptor__pb2._DESCRIPTORPROTO
_CREATECOLLECTIONRESPONSE.fields_by_name['failure_code'].enum_type = _CREATECOLLECTIONRESPONSE_FAILURECODE
_CREATECOLLECTIONRESPONSE_FAILURECODE.containing_type = _CREATECOLLECTIONRESPONSE
DESCRIPTOR.message_types_by_name['CreateCollection'] = _CREATECOLLECTION
DESCRIPTOR.message_types_by_name['CreateCollectionResponse'] = _CREATECOLLECTIONRESPONSE

CreateCollection = _reflection.GeneratedProtocolMessageType('CreateCollection', (_message.Message,), dict(
  DESCRIPTOR = _CREATECOLLECTION,
  __module__ = 'server.collection_create_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.CreateCollection)
  ))
_sym_db.RegisterMessage(CreateCollection)

CreateCollectionResponse = _reflection.GeneratedProtocolMessageType('CreateCollectionResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATECOLLECTIONRESPONSE,
  __module__ = 'server.collection_create_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.CreateCollectionResponse)
  ))
_sym_db.RegisterMessage(CreateCollectionResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
