# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/collection_delete.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/collection_delete.proto',
  package='protodb.server',
  syntax='proto3',
  serialized_pb=_b('\n\x1eserver/collection_delete.proto\x12\x0eprotodb.server\"8\n\x10\x44\x65leteCollection\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\"\x96\x01\n\x18\x44\x65leteCollectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12J\n\x0c\x66\x61ilure_code\x18\x02 \x01(\x0e\x32\x34.protodb.server.DeleteCollectionResponse.FailureCode\"\x1d\n\x0b\x46\x61ilureCode\x12\x0e\n\nINVALID_DB\x10\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DELETECOLLECTIONRESPONSE_FAILURECODE = _descriptor.EnumDescriptor(
  name='FailureCode',
  full_name='protodb.server.DeleteCollectionResponse.FailureCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_DB', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=230,
  serialized_end=259,
)
_sym_db.RegisterEnumDescriptor(_DELETECOLLECTIONRESPONSE_FAILURECODE)


_DELETECOLLECTION = _descriptor.Descriptor(
  name='DeleteCollection',
  full_name='protodb.server.DeleteCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.server.DeleteCollection.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collection', full_name='protodb.server.DeleteCollection.collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=106,
)


_DELETECOLLECTIONRESPONSE = _descriptor.Descriptor(
  name='DeleteCollectionResponse',
  full_name='protodb.server.DeleteCollectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='protodb.server.DeleteCollectionResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_code', full_name='protodb.server.DeleteCollectionResponse.failure_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DELETECOLLECTIONRESPONSE_FAILURECODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=259,
)

_DELETECOLLECTIONRESPONSE.fields_by_name['failure_code'].enum_type = _DELETECOLLECTIONRESPONSE_FAILURECODE
_DELETECOLLECTIONRESPONSE_FAILURECODE.containing_type = _DELETECOLLECTIONRESPONSE
DESCRIPTOR.message_types_by_name['DeleteCollection'] = _DELETECOLLECTION
DESCRIPTOR.message_types_by_name['DeleteCollectionResponse'] = _DELETECOLLECTIONRESPONSE

DeleteCollection = _reflection.GeneratedProtocolMessageType('DeleteCollection', (_message.Message,), dict(
  DESCRIPTOR = _DELETECOLLECTION,
  __module__ = 'server.collection_delete_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.DeleteCollection)
  ))
_sym_db.RegisterMessage(DeleteCollection)

DeleteCollectionResponse = _reflection.GeneratedProtocolMessageType('DeleteCollectionResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETECOLLECTIONRESPONSE,
  __module__ = 'server.collection_delete_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.DeleteCollectionResponse)
  ))
_sym_db.RegisterMessage(DeleteCollectionResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
