# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/collection_define.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/collection_define.proto',
  package='protodb.server',
  syntax='proto3',
  serialized_pb=_b('\n\x1eserver/collection_define.proto\x12\x0eprotodb.server\x1a google/protobuf/descriptor.proto\"8\n\x10\x44\x65\x66ineCollection\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\"\xe0\x01\n\x18\x44\x65\x66ineCollectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12J\n\x0c\x66\x61ilure_code\x18\x02 \x01(\x0e\x32\x34.protodb.server.DefineCollectionResponse.FailureCode\x12\x30\n\x06schema\x18\x03 \x01(\x0b\x32 .google.protobuf.DescriptorProto\"5\n\x0b\x46\x61ilureCode\x12\x0e\n\nINVALID_DB\x10\x00\x12\x16\n\x12INVALID_COLLECTION\x10\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DEFINECOLLECTIONRESPONSE_FAILURECODE = _descriptor.EnumDescriptor(
  name='FailureCode',
  full_name='protodb.server.DefineCollectionResponse.FailureCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_DB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_COLLECTION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=314,
  serialized_end=367,
)
_sym_db.RegisterEnumDescriptor(_DEFINECOLLECTIONRESPONSE_FAILURECODE)


_DEFINECOLLECTION = _descriptor.Descriptor(
  name='DefineCollection',
  full_name='protodb.server.DefineCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.server.DefineCollection.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collection', full_name='protodb.server.DefineCollection.collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=140,
)


_DEFINECOLLECTIONRESPONSE = _descriptor.Descriptor(
  name='DefineCollectionResponse',
  full_name='protodb.server.DefineCollectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='protodb.server.DefineCollectionResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_code', full_name='protodb.server.DefineCollectionResponse.failure_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='schema', full_name='protodb.server.DefineCollectionResponse.schema', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEFINECOLLECTIONRESPONSE_FAILURECODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=367,
)

_DEFINECOLLECTIONRESPONSE.fields_by_name['failure_code'].enum_type = _DEFINECOLLECTIONRESPONSE_FAILURECODE
_DEFINECOLLECTIONRESPONSE.fields_by_name['schema'].message_type = google_dot_protobuf_dot_descriptor__pb2._DESCRIPTORPROTO
_DEFINECOLLECTIONRESPONSE_FAILURECODE.containing_type = _DEFINECOLLECTIONRESPONSE
DESCRIPTOR.message_types_by_name['DefineCollection'] = _DEFINECOLLECTION
DESCRIPTOR.message_types_by_name['DefineCollectionResponse'] = _DEFINECOLLECTIONRESPONSE

DefineCollection = _reflection.GeneratedProtocolMessageType('DefineCollection', (_message.Message,), dict(
  DESCRIPTOR = _DEFINECOLLECTION,
  __module__ = 'server.collection_define_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.DefineCollection)
  ))
_sym_db.RegisterMessage(DefineCollection)

DefineCollectionResponse = _reflection.GeneratedProtocolMessageType('DefineCollectionResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEFINECOLLECTIONRESPONSE,
  __module__ = 'server.collection_define_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.DefineCollectionResponse)
  ))
_sym_db.RegisterMessage(DefineCollectionResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
