# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/database_list.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/database_list.proto',
  package='protodb.server',
  syntax='proto3',
  serialized_pb=_b('\n\x1aserver/database_list.proto\x12\x0eprotodb.server\"\x0f\n\rListDatabases\")\n\x15ListDatabasesResponse\x12\x10\n\x08\x64\x61tabase\x18\x01 \x03(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LISTDATABASES = _descriptor.Descriptor(
  name='ListDatabases',
  full_name='protodb.server.ListDatabases',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=61,
)


_LISTDATABASESRESPONSE = _descriptor.Descriptor(
  name='ListDatabasesResponse',
  full_name='protodb.server.ListDatabasesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.server.ListDatabasesResponse.database', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['ListDatabases'] = _LISTDATABASES
DESCRIPTOR.message_types_by_name['ListDatabasesResponse'] = _LISTDATABASESRESPONSE

ListDatabases = _reflection.GeneratedProtocolMessageType('ListDatabases', (_message.Message,), dict(
  DESCRIPTOR = _LISTDATABASES,
  __module__ = 'server.database_list_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.ListDatabases)
  ))
_sym_db.RegisterMessage(ListDatabases)

ListDatabasesResponse = _reflection.GeneratedProtocolMessageType('ListDatabasesResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTDATABASESRESPONSE,
  __module__ = 'server.database_list_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.ListDatabasesResponse)
  ))
_sym_db.RegisterMessage(ListDatabasesResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
