# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/database_define.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/database_define.proto',
  package='protodb.server',
  syntax='proto3',
  serialized_pb=_b('\n\x1cserver/database_define.proto\x12\x0eprotodb.server\"\x1e\n\x0e\x44\x65\x66ineDatabase\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xa6\x01\n\x16\x44\x65\x66ineDatabaseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12H\n\x0c\x66\x61ilure_code\x18\x02 \x01(\x0e\x32\x32.protodb.server.DefineDatabaseResponse.FailureCode\x12\x12\n\ncollection\x18\x03 \x03(\t\"\x1d\n\x0b\x46\x61ilureCode\x12\x0e\n\nINVALID_DB\x10\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DEFINEDATABASERESPONSE_FAILURECODE = _descriptor.EnumDescriptor(
  name='FailureCode',
  full_name='protodb.server.DefineDatabaseResponse.FailureCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_DB', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=218,
  serialized_end=247,
)
_sym_db.RegisterEnumDescriptor(_DEFINEDATABASERESPONSE_FAILURECODE)


_DEFINEDATABASE = _descriptor.Descriptor(
  name='DefineDatabase',
  full_name='protodb.server.DefineDatabase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protodb.server.DefineDatabase.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=78,
)


_DEFINEDATABASERESPONSE = _descriptor.Descriptor(
  name='DefineDatabaseResponse',
  full_name='protodb.server.DefineDatabaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='protodb.server.DefineDatabaseResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_code', full_name='protodb.server.DefineDatabaseResponse.failure_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collection', full_name='protodb.server.DefineDatabaseResponse.collection', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEFINEDATABASERESPONSE_FAILURECODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=247,
)

_DEFINEDATABASERESPONSE.fields_by_name['failure_code'].enum_type = _DEFINEDATABASERESPONSE_FAILURECODE
_DEFINEDATABASERESPONSE_FAILURECODE.containing_type = _DEFINEDATABASERESPONSE
DESCRIPTOR.message_types_by_name['DefineDatabase'] = _DEFINEDATABASE
DESCRIPTOR.message_types_by_name['DefineDatabaseResponse'] = _DEFINEDATABASERESPONSE

DefineDatabase = _reflection.GeneratedProtocolMessageType('DefineDatabase', (_message.Message,), dict(
  DESCRIPTOR = _DEFINEDATABASE,
  __module__ = 'server.database_define_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.DefineDatabase)
  ))
_sym_db.RegisterMessage(DefineDatabase)

DefineDatabaseResponse = _reflection.GeneratedProtocolMessageType('DefineDatabaseResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEFINEDATABASERESPONSE,
  __module__ = 'server.database_define_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.DefineDatabaseResponse)
  ))
_sym_db.RegisterMessage(DefineDatabaseResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
