# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/database_delete.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/database_delete.proto',
  package='protodb.server',
  syntax='proto3',
  serialized_pb=_b('\n\x1cserver/database_delete.proto\x12\x0eprotodb.server\"\x1e\n\x0e\x44\x65leteDatabase\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x16\x44\x65leteDatabaseResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DELETEDATABASE = _descriptor.Descriptor(
  name='DeleteDatabase',
  full_name='protodb.server.DeleteDatabase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protodb.server.DeleteDatabase.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=78,
)


_DELETEDATABASERESPONSE = _descriptor.Descriptor(
  name='DeleteDatabaseResponse',
  full_name='protodb.server.DeleteDatabaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['DeleteDatabase'] = _DELETEDATABASE
DESCRIPTOR.message_types_by_name['DeleteDatabaseResponse'] = _DELETEDATABASERESPONSE

DeleteDatabase = _reflection.GeneratedProtocolMessageType('DeleteDatabase', (_message.Message,), dict(
  DESCRIPTOR = _DELETEDATABASE,
  __module__ = 'server.database_delete_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.DeleteDatabase)
  ))
_sym_db.RegisterMessage(DeleteDatabase)

DeleteDatabaseResponse = _reflection.GeneratedProtocolMessageType('DeleteDatabaseResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETEDATABASERESPONSE,
  __module__ = 'server.database_delete_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.DeleteDatabaseResponse)
  ))
_sym_db.RegisterMessage(DeleteDatabaseResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
