# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/insert.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/insert.proto',
  package='protodb.server',
  syntax='proto3',
  serialized_pb=_b('\n\x13server/insert.proto\x12\x0eprotodb.server\"<\n\x06Insert\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\xa7\x01\n\x0eInsertResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03_id\x18\x02 \x01(\x04\x12@\n\x0c\x66\x61ilure_code\x18\x03 \x01(\x0e\x32*.protodb.server.InsertResponse.FailureCode\"5\n\x0b\x46\x61ilureCode\x12\x0e\n\nINVALID_DB\x10\x00\x12\x16\n\x12INVALID_COLLECTION\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_INSERTRESPONSE_FAILURECODE = _descriptor.EnumDescriptor(
  name='FailureCode',
  full_name='protodb.server.InsertResponse.FailureCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_DB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_COLLECTION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=216,
  serialized_end=269,
)
_sym_db.RegisterEnumDescriptor(_INSERTRESPONSE_FAILURECODE)


_INSERT = _descriptor.Descriptor(
  name='Insert',
  full_name='protodb.server.Insert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.server.Insert.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collection', full_name='protodb.server.Insert.collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='protodb.server.Insert.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=99,
)


_INSERTRESPONSE = _descriptor.Descriptor(
  name='InsertResponse',
  full_name='protodb.server.InsertResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='protodb.server.InsertResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='_id', full_name='protodb.server.InsertResponse._id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='failure_code', full_name='protodb.server.InsertResponse.failure_code', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INSERTRESPONSE_FAILURECODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=269,
)

_INSERTRESPONSE.fields_by_name['failure_code'].enum_type = _INSERTRESPONSE_FAILURECODE
_INSERTRESPONSE_FAILURECODE.containing_type = _INSERTRESPONSE
DESCRIPTOR.message_types_by_name['Insert'] = _INSERT
DESCRIPTOR.message_types_by_name['InsertResponse'] = _INSERTRESPONSE

Insert = _reflection.GeneratedProtocolMessageType('Insert', (_message.Message,), dict(
  DESCRIPTOR = _INSERT,
  __module__ = 'server.insert_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.Insert)
  ))
_sym_db.RegisterMessage(Insert)

InsertResponse = _reflection.GeneratedProtocolMessageType('InsertResponse', (_message.Message,), dict(
  DESCRIPTOR = _INSERTRESPONSE,
  __module__ = 'server.insert_pb2'
  # @@protoc_insertion_point(class_scope:protodb.server.InsertResponse)
  ))
_sym_db.RegisterMessage(InsertResponse)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
