#! /usr/bin/python

import errno
import os
import subprocess

from grpc.tools import protoc

example_protos = ["user.proto"]
protodb_protos_path = os.path.abspath("../../protos/")
protodb_server_protos_path = protodb_protos_path + "/server"

subprocess.call(["protoc", "-I", ".", "--python_out=src"] + example_protos)

grpc_cmd = ("python -m grpc.tools.protoc -I %s --python_out=src --grpc_python_out=src %s/*.proto" %
            (protodb_protos_path,
             protodb_server_protos_path))

p = subprocess.Popen(grpc_cmd,
                     shell=True,
                     stdout=subprocess.PIPE,
                     stderr=subprocess.PIPE)
stdout, stderr = p.communicate()

if stdout and not quiet:
    print "%s stdout: %s" % (grpc_cmd, stdout)

if stderr:
    print "%s stderr: %s" % (grpc_cmd, stderr)
    raise Exception(stderr)
