[package]
name = "wasm"
version = "0.1.0"
authors = ["Kevin Rosendahl <kevindrosendahl@gmail.com>"]
edition = "2018"

[dependencies]
protodb-wasm = { path = '../../crates/wasm', version = '0.1' }
wasm-bindgen = "0.2.28"

[lib]
crate-type = ["cdylib"]