# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/wasm/register.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/wasm/register.proto',
  package='protodb.wasm',
  syntax='proto3',
  serialized_pb=_b('\n\x1bprotodb/wasm/register.proto\x12\x0cprotodb.wasm\"E\n\x15RegisterModuleRequest\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04wasm\x18\x03 \x01(\x0c\"\xb4\x01\n\x16RegisterModuleResponse\x12\x42\n\nerror_code\x18\x01 \x01(\x0e\x32..protodb.wasm.RegisterModuleResponse.ErrorCode\"V\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x14\n\x10INVALID_DATABASE\x10\x02\x12\x11\n\rMODULE_EXISTS\x10\x03\x62\x06proto3')
)



_REGISTERMODULERESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='protodb.wasm.RegisterModuleResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DATABASE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODULE_EXISTS', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=211,
  serialized_end=297,
)
_sym_db.RegisterEnumDescriptor(_REGISTERMODULERESPONSE_ERRORCODE)


_REGISTERMODULEREQUEST = _descriptor.Descriptor(
  name='RegisterModuleRequest',
  full_name='protodb.wasm.RegisterModuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.wasm.RegisterModuleRequest.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protodb.wasm.RegisterModuleRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wasm', full_name='protodb.wasm.RegisterModuleRequest.wasm', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=114,
)


_REGISTERMODULERESPONSE = _descriptor.Descriptor(
  name='RegisterModuleResponse',
  full_name='protodb.wasm.RegisterModuleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='protodb.wasm.RegisterModuleResponse.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REGISTERMODULERESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=297,
)

_REGISTERMODULERESPONSE.fields_by_name['error_code'].enum_type = _REGISTERMODULERESPONSE_ERRORCODE
_REGISTERMODULERESPONSE_ERRORCODE.containing_type = _REGISTERMODULERESPONSE
DESCRIPTOR.message_types_by_name['RegisterModuleRequest'] = _REGISTERMODULEREQUEST
DESCRIPTOR.message_types_by_name['RegisterModuleResponse'] = _REGISTERMODULERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterModuleRequest = _reflection.GeneratedProtocolMessageType('RegisterModuleRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERMODULEREQUEST,
  __module__ = 'protodb.wasm.register_pb2'
  # @@protoc_insertion_point(class_scope:protodb.wasm.RegisterModuleRequest)
  ))
_sym_db.RegisterMessage(RegisterModuleRequest)

RegisterModuleResponse = _reflection.GeneratedProtocolMessageType('RegisterModuleResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERMODULERESPONSE,
  __module__ = 'protodb.wasm.register_pb2'
  # @@protoc_insertion_point(class_scope:protodb.wasm.RegisterModuleResponse)
  ))
_sym_db.RegisterMessage(RegisterModuleResponse)


# @@protoc_insertion_point(module_scope)
