# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/index/get.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protodb.index import index_pb2 as protodb_dot_index_dot_index__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/index/get.proto',
  package='protodb.index',
  syntax='proto3',
  serialized_pb=_b('\n\x17protodb/index/get.proto\x12\rprotodb.index\x1a\x19protodb/index/index.proto\"C\n\x0fGetIndexRequest\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x12\n\ncollection\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x04\"\xe3\x01\n\x10GetIndexResponse\x12=\n\nerror_code\x18\x01 \x01(\x0e\x32).protodb.index.GetIndexResponse.ErrorCode\x12#\n\x05index\x18\x02 \x01(\x0b\x32\x14.protodb.index.Index\"k\n\tErrorCode\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x14\n\x10INVALID_DATABASE\x10\x02\x12\x16\n\x12INVALID_COLLECTION\x10\x03\x12\x0e\n\nINVALID_ID\x10\x04\x62\x06proto3')
  ,
  dependencies=[protodb_dot_index_dot_index__pb2.DESCRIPTOR,])



_GETINDEXRESPONSE_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='protodb.index.GetIndexResponse.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DATABASE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_COLLECTION', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_ID', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=259,
  serialized_end=366,
)
_sym_db.RegisterEnumDescriptor(_GETINDEXRESPONSE_ERRORCODE)


_GETINDEXREQUEST = _descriptor.Descriptor(
  name='GetIndexRequest',
  full_name='protodb.index.GetIndexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='protodb.index.GetIndexRequest.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collection', full_name='protodb.index.GetIndexRequest.collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='protodb.index.GetIndexRequest.id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=136,
)


_GETINDEXRESPONSE = _descriptor.Descriptor(
  name='GetIndexResponse',
  full_name='protodb.index.GetIndexResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='protodb.index.GetIndexResponse.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='protodb.index.GetIndexResponse.index', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETINDEXRESPONSE_ERRORCODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=366,
)

_GETINDEXRESPONSE.fields_by_name['error_code'].enum_type = _GETINDEXRESPONSE_ERRORCODE
_GETINDEXRESPONSE.fields_by_name['index'].message_type = protodb_dot_index_dot_index__pb2._INDEX
_GETINDEXRESPONSE_ERRORCODE.containing_type = _GETINDEXRESPONSE
DESCRIPTOR.message_types_by_name['GetIndexRequest'] = _GETINDEXREQUEST
DESCRIPTOR.message_types_by_name['GetIndexResponse'] = _GETINDEXRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetIndexRequest = _reflection.GeneratedProtocolMessageType('GetIndexRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETINDEXREQUEST,
  __module__ = 'protodb.index.get_pb2'
  # @@protoc_insertion_point(class_scope:protodb.index.GetIndexRequest)
  ))
_sym_db.RegisterMessage(GetIndexRequest)

GetIndexResponse = _reflection.GeneratedProtocolMessageType('GetIndexResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETINDEXRESPONSE,
  __module__ = 'protodb.index.get_pb2'
  # @@protoc_insertion_point(class_scope:protodb.index.GetIndexResponse)
  ))
_sym_db.RegisterMessage(GetIndexResponse)


# @@protoc_insertion_point(module_scope)
