# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protodb/database/run_wasm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protodb/database/run_wasm.proto',
  package='protodb.database',
  syntax='proto3',
  serialized_pb=_b('\n\x1fprotodb/database/run_wasm.proto\x12\x10protodb.database\x1a google/protobuf/descriptor.proto\"\x1e\n\x0eRunWasmRequest\x12\x0c\n\x04wasm\x18\x01 \x01(\x0c\"!\n\x0fRunWasmResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])




_RUNWASMREQUEST = _descriptor.Descriptor(
  name='RunWasmRequest',
  full_name='protodb.database.RunWasmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wasm', full_name='protodb.database.RunWasmRequest.wasm', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=117,
)


_RUNWASMRESPONSE = _descriptor.Descriptor(
  name='RunWasmResponse',
  full_name='protodb.database.RunWasmResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='protodb.database.RunWasmResponse.result', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['RunWasmRequest'] = _RUNWASMREQUEST
DESCRIPTOR.message_types_by_name['RunWasmResponse'] = _RUNWASMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunWasmRequest = _reflection.GeneratedProtocolMessageType('RunWasmRequest', (_message.Message,), dict(
  DESCRIPTOR = _RUNWASMREQUEST,
  __module__ = 'protodb.database.run_wasm_pb2'
  # @@protoc_insertion_point(class_scope:protodb.database.RunWasmRequest)
  ))
_sym_db.RegisterMessage(RunWasmRequest)

RunWasmResponse = _reflection.GeneratedProtocolMessageType('RunWasmResponse', (_message.Message,), dict(
  DESCRIPTOR = _RUNWASMRESPONSE,
  __module__ = 'protodb.database.run_wasm_pb2'
  # @@protoc_insertion_point(class_scope:protodb.database.RunWasmResponse)
  ))
_sym_db.RegisterMessage(RunWasmResponse)


# @@protoc_insertion_point(module_scope)
